name: Package mod

on: push

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        persist-credentials: false
        lfs: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore REE-Lib dependencies
      run: |
        cd addons/ReachForGodot/REE-Lib/REE-Lib
        dotnet restore
    - name: Build REE-Lib
      run: |
        cd addons/ReachForGodot/REE-Lib/REE-Lib
        dotnet publish --no-restore -f net8.0 -c Release -o _out
        mkdir ../../Plugins -f
        mv _out/*.dll ../../Plugins/

    - name: Prepare files
      run: |
        rm addons/ReachForGodot/REE-Lib/ -r -force
        mkdir output
        mv addons output/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ReachForGodot
        path: "output/"
        include-hidden-files: true

    - name: ZIP files for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd output/
        7z a -mx=9 ReachForGodot.zip *

    - name: Upload files to release
      uses: softprops/action-gh-release@v2.2.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "output/*.zip"
